### ISSUE TITLE
Deploy contract v0.2

### ISSUE THREAD

**Issue by juliangruber** [filecoin-station/spark-impact-evaluator#7]
```[tasklist]
### Tasks
- [ ] Deploy contract v0.2
- [x] List participants from last 4 weeks
- [x] List participant balances
- [x] Add `.addBalances()`
- [x] Add `.setMinRewardThreshold()`
- [x] Release balances held in contract v0.1
- [x] Switch over systems
```

**Comment by juliangruber** [comment]
> List participant balances:

```bash
$ cat ~/dev/filecoin-station/spark-evaluate/0x.txt | xargs -n1 node bin/rewards-scheduled-for.js
```
